In [77]:
import numpy as np
from datetime import datetime

In [22]:
# make list of variable-length sequences
_1 = [1,2,3]
_2 = [3,2]
_3 = [2,2,2,1,2]
_4 = [3,1]

seqs0 = [_1, _2, _3, _4]
seqs0

[[1, 2, 3], [3, 2], [2, 2, 2, 1, 2], [3, 1]]

In [23]:
# find longest seq
_max_len0 = len(max(seqs0, key=len))
_max_len0

5

In [24]:
# pad seqs
def pad0(x, _max_len0):
    return x + [0] * (_max_len0 - len(x))

In [25]:
padded_seqs0 = [pad0(x, _max_len0) for x in seqs0]
padded_seqs0

[[1, 2, 3, 0, 0], [3, 2, 0, 0, 0], [2, 2, 2, 1, 2], [3, 1, 0, 0, 0]]

In [26]:
# build np matrix
matrix0 = np.asarray(padded_seqs0)
matrix0

array([[1, 2, 3, 0, 0],
       [3, 2, 0, 0, 0],
       [2, 2, 2, 1, 2],
       [3, 1, 0, 0, 0]])

In [27]:
matrix0.shape

(4, 5)

In [28]:
# repeat process but with str DNA seqs
_1 = 'GGCCGTTACACTG'
_2 = 'AGCCGTT'
_3 = 'ATTGTCCGTA'
_4 = 'TATACCGT'

seqs = [_1, _2, _3, _4]
seqs

['GGCCGTTACACTG', 'AGCCGTT', 'ATTGTCCGTA', 'TATACCGT']

In [29]:
# map nucleotides to ints
# A:1, T:2, G:3, C:4, 0:None
def map_nucs(seq):
    mapped_seq = []
    for nuc in seq:
        if nuc == 'A':
            mapped_seq.append(1)
        elif nuc == 'T':
            mapped_seq.append(2)
        elif nuc == 'G':
            mapped_seq.append(3)
        elif nuc == 'C':
            mapped_seq.append(4)
    return mapped_seq

In [30]:
seqs = [map_nucs(x) for x in seqs]
seqs

[[3, 3, 4, 4, 3, 2, 2, 1, 4, 1, 4, 2, 3],
 [1, 3, 4, 4, 3, 2, 2],
 [1, 2, 2, 3, 2, 4, 4, 3, 2, 1],
 [2, 1, 2, 1, 4, 4, 3, 2]]

In [31]:
# find longest seq
_max_len = len(max(seqs, key=len))
_max_len

13

In [32]:
# pad seqs strings
def pad(x, _max_len):
    return x + [0] * (_max_len - len(x))

In [33]:
padded_seqs = [pad(x, _max_len) for x in seqs]
padded_seqs

[[3, 3, 4, 4, 3, 2, 2, 1, 4, 1, 4, 2, 3],
 [1, 3, 4, 4, 3, 2, 2, 0, 0, 0, 0, 0, 0],
 [1, 2, 2, 3, 2, 4, 4, 3, 2, 1, 0, 0, 0],
 [2, 1, 2, 1, 4, 4, 3, 2, 0, 0, 0, 0, 0]]

In [34]:
# build np matrix
matrix = np.asarray(padded_seqs)
matrix

array([[3, 3, 4, 4, 3, 2, 2, 1, 4, 1, 4, 2, 3],
       [1, 3, 4, 4, 3, 2, 2, 0, 0, 0, 0, 0, 0],
       [1, 2, 2, 3, 2, 4, 4, 3, 2, 1, 0, 0, 0],
       [2, 1, 2, 1, 4, 4, 3, 2, 0, 0, 0, 0, 0]])

In [35]:
matrix.shape

(4, 13)

In [36]:
# unmap matrix to strings
def unmap_nucs(seq):
    # unmap [int] to str
    unmapped_seq = ''
    for nuc in seq:
        if nuc == 1:
            unmapped_seq += 'A'
        elif nuc == 2:
            unmapped_seq += 'T'
        elif nuc == 3:
            unmapped_seq += 'G'
        elif nuc == 4:
            unmapped_seq += 'C'
        elif nuc == 0:
            pass
    return unmapped_seq

In [37]:
unmapped = [unmap_nucs(x) for x in matrix]
unmapped

['GGCCGTTACACTG', 'AGCCGTT', 'ATTGTCCGTA', 'TATACCGT']

In [41]:
import gzip
from mimetypes import guess_type
from functools import partial
from Bio import SeqIO

In [42]:
input_file = '/Users/jonathanlifferth/data/bioinformatics/Divergene/question2/liver cDNA/1153-cDNA-8V8_S30_L001_R1_001.fastq.gz'

encoding = guess_type(input_file)[1]  # uses file extension
_open = partial(gzip.open, mode='rt') if encoding == 'gzip' else open

In [44]:
Left_flank = 'taacttgcagcagcaaGGC' 
Right_flank = 'GCCaacacggctcctcaaa'

Left_flank = Left_flank.upper()
Right_flank = Right_flank.upper()

In [47]:
# practice scaling matrix mapping on actual fastq data

insert_seqs = []
index = 0
with _open(input_file) as f:
    for record in SeqIO.parse(f, 'fastq'):
        if Left_flank in record.seq and Right_flank in record.seq:
            seq_start = record.seq.find(Left_flank) + len(Left_flank)
            seq_end = record.seq.find(Right_flank)
#             print('start: ', seq_start, ', end: ', seq_end)
            seq = record.seq[seq_start:seq_end]
            insert_seqs.append(str(seq))
            index += 1
print(index)
print(len(insert_seqs))

115746
115746


In [48]:
insert_seqs[0]

'CTGTACCNGCATCATACTGAC'

In [49]:
insert_seqs = [map_nucs(x) for x in insert_seqs]
len(insert_seqs)

115746

In [50]:
_max_len = len(max(insert_seqs, key=len))
_max_len

30

In [51]:
padded_insert_seqs = [pad(x, _max_len) for x in insert_seqs]
len(padded_insert_seqs)

115746

In [54]:
print(type(padded_insert_seqs))
len(padded_insert_seqs[0])

<class 'list'>


30

In [56]:
insert_matrix = np.asarray(padded_insert_seqs)
insert_matrix.shape

(115746, 30)

In [63]:
print(insert_matrix[0])
unique_seqs, counts = np.unique(insert_matrix, axis=0, return_counts=True)
print(unique_seqs.shape)
print(counts.shape)

[4 2 3 2 1 4 4 3 4 1 2 4 1 2 1 4 2 3 1 4 0 0 0 0 0 0 0 0 0 0]
(2758, 30)
(2758,)


In [66]:
unmapped_unique_seqs = [unmap_nucs(x) for x in unique_seqs]
print(unmapped_unique_seqs[0])
print(len(unmapped_unique_seqs))

AAAAAAAATCATGCGGGACGAA
2758


In [68]:
unique_seqs_dict = {unmapped_unique_seqs[i]:counts[i] for i in range(len(unmapped_unique_seqs))}
unique_seqs_dict

{'AAAAAAAATCATGCGGGACGAA': 1,
 'AAAAAAATTGTTCTTGACGTT': 1,
 'AAAAAAATCAAGCGTGACGAA': 1,
 'AAAAAAATCATACGTGACGAA': 1,
 'AAAAAAATCATTCGGGACGAA': 1,
 'AAAAAAATCATGTGTGACGAA': 1,
 'AAAAAAATCATGCGTGAAGAA': 1,
 'AAAAAAATCATGCGTGATGAA': 1,
 'AAAAAAATCATGCGTGACTAA': 1,
 'AAAAAAATCATGCGTGACGAA': 522,
 'AAAAAAATCATGCGGGACGAA': 1,
 'AAAAAAATCATCCGTGACGAA': 1,
 'AAAAAAATCCTGCGTGACGAA': 1,
 'AAAAAAAGCATGCATGACGAA': 1,
 'AAAAAATCATGCGTGACGAA': 3,
 'AAAAAATCTTCTGACAACTAC': 1,
 'AAAAAACTCATGCGTGACGAA': 1,
 'AAAAATGTTGTTACTGGTGTT': 1,
 'AAAAAGATCATGCGTGACGAA': 1,
 'AAAAACAAAGGTTTCGTTGGTGAC': 1,
 'AAAAACGTTGTGTCTGCGGGT': 1,
 'AAAATAAAAGGTTTCGTTGGTGAC': 1,
 'AAAATAATCATGCGTGAAGAA': 1,
 'AAAATTAAAGGTTTCGTTGTTGAC': 1,
 'AAAATTAAAGGTTTCGTTGGTGAC': 2,
 'AAAATTAATGGATTCGTTGGTGAC': 1,
 'AAAATTCGTGCGCTGGACCCG': 1,
 'AAAATGAAAATCACTCCGGGT': 33,
 'AAAATCAAAGTTTTCGTTGGCGAC': 1,
 'AAAATCAAAGGATTCGTTGGTGAC': 3,
 'AAAATCAAAGGTTTCGTTTGTGAC': 2,
 'AAAATCAAAGGTTTCGTTGTTGAC': 1,
 'AAAATCAAAGGTTTCGTTGGAGAC': 3,
 'AAAATCAA

In [69]:
unique_seqs_sorted = sorted(unique_seqs_dict.items(), key=lambda x: x[1], reverse=True)
unique_seqs_sorted

[('GACGTTAAACCGTACTCTATG', 7006),
 ('TACCATCATGACCATCCGATC', 6281),
 ('GACTCTGTTCGTGCTCAGAAA', 6016),
 ('ATCTTCCGTGACTCTCGTGTT', 5677),
 ('AAAGTTCGTGCTCCGAACATC', 5498),
 ('ACTAAATCTCAGATGACTGTT', 5005),
 ('CCGGGTAAAATGCAGGGTAAA', 4944),
 ('GGTGGTAACGACGCTTACATC', 4334),
 ('ATGCAGAAAGACCAGCTGAAAAAA', 3680),
 ('ATGGGTCGTCCGGCTCAGCAT', 3380),
 ('CTGTACCTGCATCATACTGAC', 2827),
 ('GTTGTTGCTGACGGTGGTCGT', 2813),
 ('CGTGGTCCGAAAGAAATCGCT', 2774),
 ('CAGGGTCATGTTCAGCAGCAG', 2755),
 ('GTTCGTGTTCAGGGTCAGCATATC', 2366),
 ('AAATTCGTTGTTAAAGCTCAG', 2339),
 ('CGTCGTGAACAGATGCTGGGT', 2117),
 ('TCTGAAATGCCGACTGGTTTC', 2011),
 ('AAAGCTCAGGTTTCTAAACCG', 1953),
 ('AAAATCAAAGGTTTCGTTGGTGAC', 1878),
 ('AAAGCTGCTATCGGTAACGAC', 1626),
 ('TCTGCTAAAAAAGTTGACACT', 1555),
 ('CCGCAGTACGCTCAGATCTCT', 1503),
 ('ATGTCTCAGAAAACTTACGTT', 1477),
 ('ATGGAAGCTGACGGTACTTTC', 1381),
 ('CATCATACTTCTACTACTCTG', 1362),
 ('GTTGACGGTAAACAGCGTTAC', 1315),
 ('ACTACTACTCCGGCTCGTGGT', 1305),
 ('TACCATTCTATGACTATGGAC', 1205),
 ('AA

In [80]:
# combine steps into single function to obtain unique seq counts for a fastq file
def get_unique_seqs(filepath):
    start = datetime.now()
    
    encoding = guess_type(filepath)[1]  # uses file extension
    _open = partial(gzip.open, mode='rt') if encoding == 'gzip' else open
    
    Left_flank = 'taacttgcagcagcaaGGC' 
    Right_flank = 'GCCaacacggctcctcaaa'

    Left_flank = Left_flank.upper()
    Right_flank = Right_flank.upper()
    
    # extract insert seqs from fastq file
    insert_seqs = []
    with _open(filepath) as f:
        for record in SeqIO.parse(f, 'fastq'):
            if Left_flank in record.seq and Right_flank in record.seq:
                seq_start = record.seq.find(Left_flank) + len(Left_flank)
                seq_end = record.seq.find(Right_flank)
                seq = record.seq[seq_start:seq_end]
                insert_seqs.append(str(seq))
    print('# of insert_seqs: ', len(insert_seqs))
    
    # map insert to ints for faster processing
    insert_seqs = [map_nucs(x) for x in insert_seqs]
    
    _max_len = len(max(insert_seqs, key=len))
    
    # pad mapped seq values for matrix
    padded_insert_seqs = [pad(x, _max_len) for x in insert_seqs]
    
    # convert padded seqs to np matrix
    insert_matrix = np.asarray(padded_insert_seqs)
    
    # isolate unique seqs and seq counts
    unique_seqs, counts = np.unique(insert_matrix, axis=0, return_counts=True)
    
    print('# of unique_seqs: ', len(unique_seqs))
    
    # unmap int values back to str
    unmapped_unique_seqs = [unmap_nucs(x) for x in unique_seqs]
    
    # create dict with unique seqs and counts
    unique_seqs_dict = {unmapped_unique_seqs[i]:counts[i] for i in range(len(unmapped_unique_seqs))}
    
    # sort dict by descending count values
    unique_seqs_sorted = sorted(unique_seqs_dict.items(), key=lambda x: x[1], reverse=True)
    
    end = datetime.now()
    elapsed = end - start
    print('elapsed time: ', elapsed)
    
    return unique_seqs_sorted


In [81]:
input_file_1153 = '/Users/jonathanlifferth/data/bioinformatics/Divergene/question2/liver cDNA/1153-cDNA-8V8_S30_L001_R1_001.fastq.gz'

result_1153 = get_unique_seqs(input_file)
result_1153

# of insert_seqs:  115746
# of unique_seqs:  2758
elapsed time:  0:00:08.188137


[('GACGTTAAACCGTACTCTATG', 7006),
 ('TACCATCATGACCATCCGATC', 6281),
 ('GACTCTGTTCGTGCTCAGAAA', 6016),
 ('ATCTTCCGTGACTCTCGTGTT', 5677),
 ('AAAGTTCGTGCTCCGAACATC', 5498),
 ('ACTAAATCTCAGATGACTGTT', 5005),
 ('CCGGGTAAAATGCAGGGTAAA', 4944),
 ('GGTGGTAACGACGCTTACATC', 4334),
 ('ATGCAGAAAGACCAGCTGAAAAAA', 3680),
 ('ATGGGTCGTCCGGCTCAGCAT', 3380),
 ('CTGTACCTGCATCATACTGAC', 2827),
 ('GTTGTTGCTGACGGTGGTCGT', 2813),
 ('CGTGGTCCGAAAGAAATCGCT', 2774),
 ('CAGGGTCATGTTCAGCAGCAG', 2755),
 ('GTTCGTGTTCAGGGTCAGCATATC', 2366),
 ('AAATTCGTTGTTAAAGCTCAG', 2339),
 ('CGTCGTGAACAGATGCTGGGT', 2117),
 ('TCTGAAATGCCGACTGGTTTC', 2011),
 ('AAAGCTCAGGTTTCTAAACCG', 1953),
 ('AAAATCAAAGGTTTCGTTGGTGAC', 1878),
 ('AAAGCTGCTATCGGTAACGAC', 1626),
 ('TCTGCTAAAAAAGTTGACACT', 1555),
 ('CCGCAGTACGCTCAGATCTCT', 1503),
 ('ATGTCTCAGAAAACTTACGTT', 1477),
 ('ATGGAAGCTGACGGTACTTTC', 1381),
 ('CATCATACTTCTACTACTCTG', 1362),
 ('GTTGACGGTAAACAGCGTTAC', 1315),
 ('ACTACTACTCCGGCTCGTGGT', 1305),
 ('TACCATTCTATGACTATGGAC', 1205),
 ('AA

In [82]:
input_file_1017 = '/Users/jonathanlifferth/data/bioinformatics/Divergene/question2/liver cDNA/1017-cDNA-8V8_S29_L001_R1_001.fastq.gz'

result_1017 = get_unique_seqs(input_file_1017)
result_1017

# of insert_seqs:  277729
# of unique_seqs:  12092
elapsed time:  0:00:22.837205


[('GTTGTTGTTCCGCGTATGGCT', 1757),
 ('CCGTACAAAGGTCGTGGTGACTCT', 1627),
 ('GGTATCCATCGTGTTCAGGAC', 1450),
 ('CGTCCTCAGGACTCTATCCAG', 1373),
 ('GCTCCGCAGCGTTTCGAAGTT', 1223),
 ('GACCGTTACCATAACCAGGTTACT', 1174),
 ('ACTGCTCGTTCTGAACGTCCG', 1132),
 ('ATCGGTATGTCTCAGCCGGCT', 1127),
 ('ATGGTTGTTACTCAGATGACT', 1114),
 ('TACAACCAGTCTCTGGAACGT', 1102),
 ('ATCACTGACGGTCGTATGCTG', 1084),
 ('ACTGGTGTTCCGACTTCTATC', 1079),
 ('GCTGTTATCGGTTTCTCTAAA', 1078),
 ('CTGGACATCTCTCCGCATGAC', 1044),
 ('GTTCAGTCTAACATGATGGGT', 1036),
 ('ACTGTTTACCCGGTTACTGCT', 1033),
 ('CAGGCTGTTCAGACTCGTCCG', 980),
 ('GACGTTGGTGCTATGCATGTT', 965),
 ('ACTGTTTCTGGTCATACTATC', 960),
 ('GTTCCGATGAACGCTCATCAG', 960),
 ('CATTCTCCGGCTCAGTTCAAC', 939),
 ('CAGACTGCTGACTCTGTTTTCTAC', 931),
 ('GCTTCTCTGAACGTTCAGGTT', 918),
 ('CCGGTTGTTAACTCTATGATC', 891),
 ('ACTCGTGCTTACGACCCGCAG', 887),
 ('TCTGTTAAAATCCGTCTGGAC', 887),
 ('AAACGTTTCGCTGGTGTTGAA', 885),
 ('ATGAACCGTGACCGTCCGTCT', 874),
 ('CATATGGCTGTTGAATCTCTG', 870),
 ('GGTCAGATGCGTCCG

In [83]:
import os

In [85]:
target_dir = '/Users/jonathanlifferth/data/bioinformatics/Divergene/question2/liver cDNA'

paths = []
for root, dirs, files in os.walk(target_dir):
    for file in files:
        if file.endswith('fastq.gz'):
            paths.append(os.path.join(root,file))            
paths.sort()
print(paths)

for path in paths:
    key = path.split('/')[-1][:4]
    print(key)

['/Users/jonathanlifferth/data/bioinformatics/Divergene/question2/liver cDNA/1017-cDNA-8V8_S29_L001_R1_001.fastq.gz', '/Users/jonathanlifferth/data/bioinformatics/Divergene/question2/liver cDNA/1027-cDNA-8V8_S25_L001_R1_001.fastq.gz', '/Users/jonathanlifferth/data/bioinformatics/Divergene/question2/liver cDNA/1032-cDNA-8V8_S26_L001_R1_001.fastq.gz', '/Users/jonathanlifferth/data/bioinformatics/Divergene/question2/liver cDNA/1153-cDNA-8V8_S30_L001_R1_001.fastq.gz', '/Users/jonathanlifferth/data/bioinformatics/Divergene/question2/liver cDNA/1163-cDNA-8V8_S27_L001_R1_001.fastq.gz', '/Users/jonathanlifferth/data/bioinformatics/Divergene/question2/liver cDNA/1168-cDNA-8V8_S28_L001_R1_001.fastq.gz']
1017
1027
1032
1153
1163
1168


In [86]:
input_1027 = paths[1]

result_1027 = get_unique_seqs(input_1027)
result_1027

# of insert_seqs:  289511
# of unique_seqs:  14560
elapsed time:  0:00:20.500782


[('ATGGACGTTCGTCAGGTTCAT', 1276),
 ('TCTCGTGGTACTCCTGTTGCT', 1255),
 ('TGGTCTGACGGTCGTATGACT', 1231),
 ('GTTCAGCATGCCAAATCTTCT', 1175),
 ('CGTAACGGTGACACTAACCTG', 1010),
 ('ATCATGTACCATGAAACTGGT', 933),
 ('TACCGTATGGGTGAAGCTATCTCT', 933),
 ('GTTCCGTTCTACAAACCGGAA', 863),
 ('CATGCTAAAGCTTACCAGGGT', 855),
 ('GGTGTTGGTCAGTCTTTCCAG', 813),
 ('CTGAAACCGCATACTACTACT', 779),
 ('GCTCATTTCCGTAAACCGAAC', 765),
 ('TTCGTTCAGCGTGGTGTTATC', 737),
 ('AACAACGGTCGTGGTCCGGAA', 736),
 ('GCTCGTGTTCATGGTGGTGAC', 734),
 ('CAGCTGGTTAAACTCACTAAA', 734),
 ('GAACGTCTGGTTTCTGCTAAA', 733),
 ('TACGACTACGACATCGTTCAG', 730),
 ('AAAGGTCGTTCTGACTCTTCT', 729),
 ('GGTGCTGACTCTAAAAAACAG', 714),
 ('AAACATCAGCTGACTGGTTCT', 698),
 ('GGTCCGACTCAGACTATGATGGTT', 698),
 ('ATGCATACTGCTGACAACAAA', 697),
 ('GCTTACCTGGGTACTGTTCGT', 697),
 ('TTCACTGGTCGTCCGGCTGAC', 687),
 ('GAAGTTAACGGTGTTGAATACCCGTCT', 679),
 ('GAATTCATCCCGCCGATGATG', 676),
 ('ACTGGTTCTAAAGAAGTTTTC', 672),
 ('ACTCTGGTTGTTAACACTGGT', 663),
 ('AAAACTGTTGGTCAGCTGATG',